//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Call.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<int> price { get; set; }
        public string picture { get; set; }
        public string category { get; set; }
    }
}
